[package]
name = "lama_rts"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = "0.9.0"
once_cell = "1.16.0"
rust-i18n = "0.6.1"