name: Rust

on: [pull_request]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install dev dependancy
      run: sudo apt-get install -y libudev libasound2-dev portaudio19-dev build-essential libpulse-dev libdbus-1-dev
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
